
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Aug 15 13:38:39 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 21;
  public static final int CONST = 3;
  public static final int ASSIGNMENT = 12;
  public static final int NOT_EQUAL = 34;
  public static final int CONTINUE = 47;
  public static final int GREATER = 40;
  public static final int LPAREN = 26;
  public static final int LESS = 37;
  public static final int MINUS = 13;
  public static final int RPAREN = 27;
  public static final int AND = 35;
  public static final int SEMICOLON = 9;
  public static final int OR = 48;
  public static final int COMMA = 10;
  public static final int CLASS = 45;
  public static final int INC = 18;
  public static final int DIV = 16;
  public static final int LESS_EQUAL = 43;
  public static final int PLUS = 14;
  public static final int IF = 33;
  public static final int DOT = 11;
  public static final int FINDANY = 8;
  public static final int EOF = 0;
  public static final int RETURN = 46;
  public static final int EQUAL = 36;
  public static final int GREATER_EQUAL = 42;
  public static final int LAMBDA = 38;
  public static final int NEW = 7;
  public static final int error = 1;
  public static final int MUL = 15;
  public static final int NUMBER = 20;
  public static final int MOD = 17;
  public static final int BREAK = 39;
  public static final int IDENT = 23;
  public static final int VOID = 4;
  public static final int FOREACH = 44;
  public static final int COLON = 31;
  public static final int LBRACE = 24;
  public static final int ELSE = 32;
  public static final int LSQUARE = 28;
  public static final int READ = 5;
  public static final int WHILE = 41;
  public static final int RSQUARE = 29;
  public static final int RBRACE = 25;
  public static final int EXTENDS = 30;
  public static final int PROG = 2;
  public static final int BOOL_CONST = 22;
  public static final int DEC = 19;
  public static final int PRINT = 6;
}

